### ISSUE TITLE
String schemas with `.trim()` produce values with spaces before or after

### ISSUE THREAD

**Issue by flavianh** [DavidTimms/zod-fast-check#13]
This schema:

```typescript
const image = z.string().trim().nonempty().endsWith(".png")
```

Can produce the value ` .png` when used with an arbitrary. I'm preventing it with `.filter` from fast-check but this is not ideal as I'd like my tests not to depend on knowledge of the schema.

Should it be baked in the library? I can participate but would need a few pointers.

**Comment by flavianh** [comment]
@DavidTimms any thoughts on this?

**Comment by DavidTimms** [comment]
Hi @flavianh. Sorry for the delay in getting back to you about this.

The library does support the `.trim()` method, but since it is a transformation, you need to use `.outputOf` to generate the arbitrary if you want it to produce strings without leading or trailing whitespace.

The value ` .png` is a valid _input_ to the schema you provided, but it is not a valid _output_. If you parsed it with that schema, it would return the string `.png`.

I hope that helps. Let me know if you have any other questions.

**Comment by flavianh** [comment]
Ooh, I get it! Rereading the documentation, it makes complete sense. Maybe a specific example underlying the difference between inputOf and outputOf in the README would help :). Thanks a lot, I'll change the relevant outputOfs
